% This LilyPond file was generated by Rosegarden 14.02
\include "nederlands.ly"
\version "2.6.0"
\header {
    copyright =  \markup { "Copyright "\char ##x00A9" xxxx Copyright Holder" }
    subtitle = "not yet subtitled"
    title = "Not Yet Titled"
    tagline = "Created using Rosegarden 14.02 and LilyPond"
}
#(set-global-staff-size 32)
#(set-default-paper-size "a4")
global = { 
    \time 4/4
    \skip 1 
}
globalTempo = {
    \override Score.MetronomeMark #'transparent = ##t
    \tempo 4 = 120  
}
\score {
    << % common
        % Force offset of colliding notes in chords:
        \override Score.NoteColumn #'force-hshift = #1.0
        % Allow fingerings inside the staff (configured from export options):
        \override Score.Fingering #'staff-padding = #'()

        \context Staff = "track 4" << 
            \set Staff.instrument = \markup { \center-column { " " } }
            \set Staff.midiInstrument = "Acoustic Grand Piano"
            \set Score.skipBars = ##t
            \set Staff.printKeyCancellation = ##f
            \new Voice \global
            \new Voice \globalTempo

            \context Voice = "voice 1" {
                \override Voice.TextScript #'padding = #2.0
                \override MultiMeasureRest #'expand-limit = 1

                
                \clef "treble"
                \key c \major
                g' 4 d'' b' g'  |
                \bar "|."
            } % Voice
        >> % Staff (final) ends

    >> % notes

    \layout {
        indent = 3.0\cm
short-indent = 1.5\cm
        \context { \Staff \RemoveEmptyStaves }
        \context { \GrandStaff \accepts "Lyrics" }
    }
%     uncomment to enable generating midi file from the lilypond source
%         \midi {
%             \tempo 4 = 120
%         } 
\midi {}
} % score
