% This LilyPond file was generated by Rosegarden 14.02
\include "nederlands.ly"
\version "2.6.0"
\header {
    copyright =  \markup { "Copyright "\char ##x00A9" xxxx Copyright Holder" }
    subtitle = "not yet subtitled"
    title = "Not Yet Titled"
    tagline = "Created using Rosegarden 14.02 and LilyPond"
}
#(set-global-staff-size 32)
#(set-default-paper-size "a4")
global = { 
    \time 4/4
    \skip 1 
}
globalTempo = {
    \override Score.MetronomeMark #'transparent = ##t
    \tempo 4 = 120  
}
\score {
    << % common
        % Force offset of colliding notes in chords:
        \override Score.NoteColumn #'force-hshift = #1.0
        % Allow fingerings inside the staff (configured from export options):
        \override Score.Fingering #'staff-padding = #'()

        \context Staff = "track 1" << 
            \set Staff.instrument = \markup { \center-column { " " } }
            \set Staff.midiInstrument = "Acoustic Grand Piano"
            \set Score.skipBars = ##t
            \set Staff.printKeyCancellation = ##f
            \new Voice \global
            \new Voice \globalTempo

            \context Voice = "voice 1" {
                \override Voice.TextScript #'padding = #2.0
                \override MultiMeasureRest #'expand-limit = 1
                \once \override Staff.TimeSignature #'style = #'() 
                \time 4/4
                
                \clef "treble"
                \key c \major
                c' 4 c' e' e'  |
            } % Voice

            \context Voice = "voice 2" {
                \override Voice.TextScript #'padding = #2.0
                \override MultiMeasureRest #'expand-limit = 1

                \skip 1 
                \clef "treble"
                \key c \major
                g' 4 g' e' r  |
            } % Voice

            \context Voice = "voice 3" {
                \override Voice.TextScript #'padding = #2.0
                \override MultiMeasureRest #'expand-limit = 1

                \skip 1*2 
                \clef "treble"
                \key c \major
                f' 4 f' d' d'  |
            } % Voice

            \context Voice = "voice 4" {
                \override Voice.TextScript #'padding = #2.0
                \override MultiMeasureRest #'expand-limit = 1

                \skip 1*3 
                \clef "treble"
                \key c \major
                b 4 b g r  |
            } % Voice

            \context Voice = "voice 5" {
                \override Voice.TextScript #'padding = #2.0
                \override MultiMeasureRest #'expand-limit = 1

                \skip 1*4 
%% 5
                \clef "treble"
                \key c \major
                c' 4 c' e' e'  |
            } % Voice

            \context Voice = "voice 6" {
                \override Voice.TextScript #'padding = #2.0
                \override MultiMeasureRest #'expand-limit = 1

                \skip 1*5 
                \clef "treble"
                \key c \major
                g' 4 g' e' r  |
            } % Voice

            \context Voice = "voice 7" {
                \override Voice.TextScript #'padding = #2.0
                \override MultiMeasureRest #'expand-limit = 1

                \skip 1*6 
                \clef "treble"
                \key c \major
                c'' 4 c'' fis' fis'  |
            } % Voice

            \context Voice = "voice 8" {
                \override Voice.TextScript #'padding = #2.0
                \override MultiMeasureRest #'expand-limit = 1

                \skip 1*7 
                \clef "treble"
                \key c \major
                g' 4 r g r  |
                \bar "|."
            } % Voice
        >> % Staff (final) ends

    >> % notes

    \layout {
        indent = 3.0\cm
short-indent = 1.5\cm
        \context { \Staff \RemoveEmptyStaves }
        \context { \GrandStaff \accepts "Lyrics" }
    }
%     uncomment to enable generating midi file from the lilypond source
%         \midi {
%             \tempo 4 = 120
%         } 
} % score
